# Generated by Django 3.2.6 on 2021-08-10 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.TextField()),
                ('type', models.TextField()),
                ('note', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('note', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('harvest_time', models.SmallIntegerField(null=True)),
                ('note', models.TextField(default='')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.type')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('planting_data', models.DateField()),
                ('note', models.TextField(default='')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.variant')),
            ],
        ),
    ]
