# Generated by Django 3.2.6 on 2021-08-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.TextField(),
        ),
    ]
