# Generated by Django 3.2.6 on 2021-08-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_alter_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='author',
            field=models.TextField(null=True),
        ),
    ]
