# Generated by Django 3.2.6 on 2021-08-15 18:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_alter_actions_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tree',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='broker.variant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='broker.type'),
        ),
    ]
