# Generated by Django 3.2.6 on 2021-08-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_auto_20210815_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='variant',
            name='harvest_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='broker.harvesttime'),
        ),
    ]
